### ISSUE TITLE
The docker image is not working

### ISSUE THREAD

**Issue by tanruixiang** [korandoru/hawkeye#107]
```
docker run -it --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native format
java.lang.Exception: git check-ignore failed:

	at io.korandoru.hawkeye.core.GitHelper.filterIgnoredFiles(GitHelper.java:101)
	at io.korandoru.hawkeye.core.LicenseProcessor.call(LicenseProcessor.java:81)
	at io.korandoru.hawkeye.command.HawkEyeCommandFormat.call(HawkEyeCommandFormat.java:48)
	at io.korandoru.hawkeye.command.HawkEyeCommandFormat.call(HawkEyeCommandFormat.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.korandoru.hawkeye.command.HawkEyeCommandMain.main(HawkEyeCommandMain.java:30)
```

**Comment by tisonkun** [comment]
Fixed at https://github.com/korandoru/hawkeye/pull/108.

The issue you reported is about "no files ignored returns 1".

**Comment by tisonkun** [comment]
While we have an unrelated issue that we may handle symbol links more properly.

I'm thinking if we should skip checking symbol links and files under them if it links to a dir; because if the link is within baseDir, we should list it in other paths anyway, and if the link is outside baseDir, we should not check it.
