### ISSUE TITLE
Move HawkEye project version Java constant to hawkeye-core

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#85]
It's now under `hawkeye-command` but it should be in the core module for any other modules usage.

https://github.com/korandoru/hawkeye/blob/e75b11d74e54026b42767923ac5d29e0195c4878/hawkeye-command/src/main/java/io/korandoru/hawkeye/command/CommandConstants.java#L24-L40

Originally made by https://github.com/korandoru/hawkeye/pull/79.

**Comment by tisonkun** [comment]
This should also fix a bug that:

```
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v3 -V
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.korandoru.hawkeye.command.HawkEyeVersionProvider.getVersion(HawkEyeVersionProvider.java:24)
	at picocli.CommandLine$Model$CommandSpec.version(CommandLine.java:7032)
	at picocli.CommandLine.printVersionHelp(CommandLine.java:2749)
	at picocli.CommandLine.executeHelpRequest(CommandLine.java:1920)
	at picocli.CommandLine.executeHelpRequest(CommandLine.java:1909)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2176)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.korandoru.hawkeye.command.HawkEyeCommandMain.main(HawkEyeCommandMain.java:35)
Caused by: java.io.UncheckedIOException: cannot load hawkeye properties file: hawkeye.properties
	at io.korandoru.hawkeye.command.CommandConstants.<clinit>(CommandConstants.java:37)
	... 9 more
Caused by: java.io.IOException: java.lang.NullPointerException: inStream parameter is null
	... 10 more
Caused by: java.lang.NullPointerException: inStream parameter is null
	at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base@17.0.5/java.util.Properties.load(Properties.java:407)
	at io.korandoru.hawkeye.command.CommandConstants.<clinit>(CommandConstants.java:32)
	... 9 more

```
